server.port: 8080
management.endpoints.web.exposure.include: health,auditevents,beans,caches,conditions,configprops,env,flyway,heapdump,httptrace,info,integrationgraph,jolokia,logfile,loggers,liquibase,metrics,mappings,prometheus,quartz,scheduledtasks,sessions,shutdown,startup,threaddump

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/hellodb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&noAccessToProcedureBodies=true&allowPublicKeyRetrieval=true
    username: auth_dbuser
    password: pass1234
    hikari:
      maximum-pool-size: 100
      connection-timeout: 6000
  zipkin:
    enabled: false
    baseUrl: http://zipkin:9411
  cloud:
    loadbalancer:
      ribbon:
        # to enable BlockLoadBalancer
        enabled: false
      health-check:
        initial-delay: 0
        interval: 15000 #ms
        refetch-instances-interval: 60000 #ms
        refetch-instances: true
        repeat-health-check: true
eureka:
  client:
    enabled: false # default = true
    service-url:
      defaultZone: http://eureka:8761/eureka/

auth-service:
  service-name: auth-service
  api-version: 1.0
  # NEVER OVERRIDE THIS VALUE IN RUNTIME
  api-base-url: /api/1.0
  version-description: spring cloud support.
  model-mapper-location: classpath:mapper/*-Mapper.xml
  options:
    echo-login-info: true
    enable-debug-endpoint: true
    accept-expired-auth-token: false
    model:
      user:
        id-generation-strategy: ID_TABLE
  password:
    charset: UTF-8
    hash-algo: SHA-256
  jwt:
    jws-algorithm-name: ES256K
    private-key-PEM:
      -----BEGIN PRIVATE KEY-----
      MIGEAgEAMBAGByqGSM49AgEGBSuBBAAKBG0wawIBAQQgjZ+mQMBI3V/BRfTM4Rx2
      0oiqtdUw7j6mPi5wg+AgROihRANCAAT4W3cDMH7EE1qgE5hTR+Pf6YCesz5pggDw
      xVlX+zbyofqYZxR+uoacoy7u34RWZM/R/dEY53qw7UCeGyqQvMKt
      -----END PRIVATE KEY-----
    public-key-PEM:
      -----BEGIN PUBLIC KEY-----
      MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE+Ft3AzB+xBNaoBOYU0fj3+mAnrM+aYIA
      8MVZV/s28qH6mGcUfrqGnKMu7t+EVmTP0f3RGOd6sO1AnhsqkLzCrQ==
      -----END PUBLIC KEY-----
    token-valid-time-sec: 300
    token-issuer: com.yu

---
spring:
  profiles: production
  datasource:
    username: auth_dbuser
    password: <YOUR_DB_PASSWORD>
auth-service:
  options:
    enable-debug-endpoint: false
    accept-expired-auth-token: false
  jwt:
    private-key-PEM:
      <YOUR PRIVATE KEY>
    public-key-PEM:
      <YOUR PUBLIC KEY>
---
spring:
  profiles: enable_spring_cloud
  zipkin:
    enabled: true
eureka:
  client:
    enabled: true